import { readFileSync } from 'fs';
import path from 'path';

// ============================================================================
// Live dictionaryFrequency lookup — same Zipf corpus data and normalization
// formula as lib/db/seeds/subtlex.ts's one-off bulk backfill script, but
// queried in-process for words created at import time instead of only being
// applied retroactively via `npm run db:seed:freq`.
//
// Data source: lib/db/seeds/data/wordfreq_{code}.json, generated by
// scripts/export_wordfreq.py from the `wordfreq` Python package (top 100k
// tokens per language).
//
// KNOWN LIMITATION — the corpus keys are NOT lemmatized. `wordfreq` scores
// literal surface forms exactly as it found them in real text, with no idea
// what a "lemma" is: a Spanish verb like "hablar" has its frequency spread
// across "habla", "hablo", "hablando", "hablé", "hablar", etc. as separate,
// independent entries, each individually lower than the verb's true combined
// usage. This lookup queries by lemma (e.g. "hablar"), so it only sees that
// one entry's score, not the sum across all its inflected forms. The effect
// is small for lightly-inflected English but real for RU/ES/FR, where a
// common verb's infinitive/dictionary form can score lower than its actual
// commonality warrants. Fixing this properly would mean regenerating these
// JSON files with each scored token first run through this app's own
// lemmatizer (the same NLP pipeline that processes texts) and summing
// frequencies per lemma — not done as of this writing; flagged here instead
// so a future change to this file doesn't accidentally paper over it.
// ============================================================================

const DATA_DIR = path.join(process.cwd(), 'lib', 'db', 'seeds', 'data');

type FreqMap = Record<string, number>;

// Loaded once per warm server instance, not once per request — these files
// are 1.5-2.4MB each, not worth re-reading and re-parsing on every import.
const freqMapCache = new Map<string, FreqMap>();

function loadFreqMap(languageCode: string): FreqMap {
  const cached = freqMapCache.get(languageCode);
  if (cached) return cached;

  let map: FreqMap = {};
  try {
    const raw = readFileSync(path.join(DATA_DIR, `wordfreq_${languageCode}.json`), 'utf-8');
    map = JSON.parse(raw) as FreqMap;
  } catch {
    // No corpus file for this language code — callers fall back to whatever
    // the caller provided, or the schema default.
  }
  freqMapCache.set(languageCode, map);
  return map;
}

function zipfToFrequency(zipf: number): number {
  return Math.min(100, Math.round((zipf / 7) * 100));
}

/**
 * Looks up a lemma's dictionaryFrequency (0-100 commonality score) from the
 * corpus data for the given language code. Returns undefined if the lemma
 * has no entry (rare word, proper noun, or a language with no corpus file).
 * See the KNOWN LIMITATION note at the top of this file — this is a
 * surface-form lookup keyed by lemma, not a true lemma-aggregated frequency.
 */
export function lookupDictionaryFrequency(languageCode: string, lemma: string): number | undefined {
  const zipf = loadFreqMap(languageCode)[lemma];
  return zipf !== undefined ? zipfToFrequency(zipf) : undefined;
}
