import { readFileSync } from 'fs';
import path from 'path';

// ============================================================================
// Live dictionaryFrequency lookup — same Zipf corpus data and normalization
// formula as lib/db/seeds/subtlex.ts's one-off bulk backfill script, but
// queried in-process for words created at import time instead of only being
// applied retroactively via `npm run db:seed:freq`.
//
// Data source: lib/db/seeds/data/wordfreq_{code}.json, generated by
// scripts/export_wordfreq.py from the `wordfreq` Python package (top 100k
// tokens per language).
//
// KNOWN LIMITATION — the corpus keys are NOT lemmatized. `wordfreq` scores
// literal surface forms exactly as it found them in real text, with no idea
// what a "lemma" is: a Spanish verb like "hablar" has its frequency spread
// across "habla", "hablo", "hablando", "hablé", "hablar", etc. as separate,
// independent entries, each individually lower than the verb's true combined
// usage. This lookup queries by lemma (e.g. "hablar"), so it only sees that
// one entry's score, not the sum across all its inflected forms. The effect
// is small for lightly-inflected English but real for RU/ES/FR, where a
// common verb's infinitive/dictionary form can score lower than its actual
// commonality warrants. Fixing this properly would mean regenerating these
// JSON files with each scored token first run through this app's own
// lemmatizer (the same NLP pipeline that processes texts) and summing
// frequencies per lemma — not done as of this writing; flagged here instead
// so a future change to this file doesn't accidentally paper over it.
// ============================================================================

const DATA_DIR = path.join(process.cwd(), 'lib', 'db', 'seeds', 'data');

type FreqMap = Record<string, number>;

// Loaded once per warm server instance, not once per request — these files
// are 1.5-2.4MB each, not worth re-reading and re-parsing on every import.
const freqMapCache = new Map<string, FreqMap>();

function loadFreqMap(languageCode: string): FreqMap {
  const cached = freqMapCache.get(languageCode);
  if (cached) return cached;

  let map: FreqMap = {};
  try {
    const raw = readFileSync(path.join(DATA_DIR, `wordfreq_${languageCode}.json`), 'utf-8');
    map = JSON.parse(raw) as FreqMap;
  } catch {
    // No corpus file for this language code — callers fall back to whatever
    // the caller provided, or the schema default.
  }
  freqMapCache.set(languageCode, map);
  return map;
}

function zipfToFrequency(zipf: number): number {
  return Math.min(100, Math.round((zipf / 7) * 100));
}

/**
 * Looks up a lemma's dictionaryFrequency (0-100 commonality score) from the
 * corpus data for the given language code. Returns undefined if the lemma
 * has no entry (rare word, proper noun, or a language with no corpus file).
 * See the KNOWN LIMITATION note at the top of this file — this is a
 * surface-form lookup keyed by lemma, not a true lemma-aggregated frequency.
 */
export function lookupDictionaryFrequency(languageCode: string, lemma: string): number | undefined {
  const zipf = loadFreqMap(languageCode)[lemma];
  return zipf !== undefined ? zipfToFrequency(zipf) : undefined;
}

// ============================================================================
// Frequency percentile ("Top X%") — for the frequency tier badge's tooltip.
//
// Deliberately keyed by SCORE (0-100), not by lemma: a word's
// dictionaryFrequency can be hand-edited via AddVocabularyModal, decoupled
// from any corpus lookup. Keying by score means the percentile shown always
// matches whatever score is actually stored/displayed for that word, corpus
// or user-entered — "what fraction of this language's top 100k words score
// at or above N" is well-defined either way.
// ============================================================================

/** Index 0-100 -> percentage of corpus entries scoring >= that index, i.e.
 * the "top X%" figure for a word with exactly that dictionaryFrequency score. */
type PercentileTable = number[];

const percentileTableCache = new Map<string, PercentileTable | null>();

function buildPercentileTable(languageCode: string): PercentileTable | null {
  const freqMap = loadFreqMap(languageCode);
  const zipfValues = Object.values(freqMap);
  const total = zipfValues.length;
  if (total === 0) return null;

  const countAtScore = new Array<number>(101).fill(0);
  for (const zipf of zipfValues) {
    countAtScore[zipfToFrequency(zipf)] += 1;
  }

  const table = new Array<number>(101).fill(0);
  let runningCount = 0;
  for (let score = 100; score >= 0; score--) {
    runningCount += countAtScore[score];
    table[score] = (runningCount / total) * 100;
  }
  return table;
}

function getPercentileTable(languageCode: string): PercentileTable | null {
  if (percentileTableCache.has(languageCode)) {
    return percentileTableCache.get(languageCode)!;
  }
  const table = buildPercentileTable(languageCode);
  percentileTableCache.set(languageCode, table);
  return table;
}

/**
 * Returns the "top X%" percentile for a given dictionaryFrequency score
 * (0-100), derived from this language's corpus score distribution. Returns
 * undefined when the language has no corpus data, or the score is the
 * "not found in corpus" sentinel (0) — callers should fall back to a
 * "rare / not in corpus" message rather than showing 0 as a percentile.
 */
export function lookupFrequencyPercentile(
  languageCode: string,
  score: number | null | undefined
): number | undefined {
  if (!score) return undefined;
  const table = getPercentileTable(languageCode);
  if (!table) return undefined;
  const clamped = Math.min(100, Math.max(0, Math.round(score)));
  return table[clamped];
}
